spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
    url: jdbc:h2:mem:schema
    username: sa
    password: password
    driverClassName: org.h2.Driver
